### PR TITLE
Add WP's image align & wrapping CSS

### PR DESCRIPTION
**Pull request by drawcard**
This CSS adds basic image classes for images placed inside regular WP content widgets, as per: https://codex.wordpress.org/Styling_Images_in_Posts_and_Pages

### CODE REVIEW

**Comment by drawcard** [comment]
I thought it might be a good idea to add in more missing CSS that is core to WP, eg caption and accessibility classes. Otherwise tools like Theme Check have a grumble when you try to validate your theme.

**Comment by cstibi** [comment]
Will you integrate these fine .CSS blocks into ElementorHelloTheme or have to copy/past it into customizer/custom CSS block?

**Comment by cstibi** [comment]
The standard wp gallery is also not supported by Hello theme's .CSS
Inserting a 2-3-4 column gallery, the result: images appears only in one column.
Is there any standard WP CSS for this problem too?
thanks,
cstibi

**Comment by matipojo** [comment]
Hi, We added all WordPress Standard CSS.
Look at https://github.com/pojome/elementor-hello-theme/pull/24

**Pull request closed without merging**
